services:
  - type: web
    name: health-analysis-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: postgresql://localhost:5432/health_analysis
      - key: OPENAI_API_KEY
        sync: false  # Set this in Render dashboard
      - key: PYTHON_VERSION
        value: "3.12"
    healthCheckPath: /api/health 